### ISSUE TITLE
CORS Headers

### ISSUE THREAD

**Issue by shaardie** [emissions-api/infrastructure#19]
Since we are a API which will be called by other websites, we probably need [CORS Headers](https://de.wikipedia.org/wiki/Cross-Origin_Resource_Sharing).

**Comment by lkiesow** [comment]
yep, something like this:

https://github.com/opencast/opencast-project-infrastructure/blob/fca4ed97285e1f7292a4a7ea0e51e191afe8c88c/ansible-allinone-demo-vm/roles/nginx/templates/nginx.conf#L158-L162
