### ISSUE TITLE
Email Addresses

### ISSUE THREAD

**Issue by shaardie** [emissions-api/infrastructure#2]
Currently, our mail addresses are not working properly. So let's use this status and make a proper setup for this:

* [x] Fix DNS Entry
* [x] Forward mails to the interested members
* [x] Generate valid TLS-Certificates
* [x] Create info@emissions-api.org
* [x] Create security@emissions-api.org

**Comment by shaardie** [comment]
@lkiesow I guess this is all done?

**Comment by lkiesow** [comment]
yes
