### ISSUE TITLE
Find an organization to host this

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/infrastructure#4]
For the sake of long-term survival, it would be great to find an organization interested in data and API which would be interested in hosting the service.

If possible, when we approach them we should have:

- a running prototype
- a rough estimate of required resources

**Comment by tibroc** [comment]
We should discuss if AWS would be a suitable infrastructure for us. 

Via @lkiesow :
https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/

**Comment by lkiesow** [comment]
It's now hosted at Osnabrück University
