### ISSUE TITLE
HTTPS via Let's Encrypt

### ISSUE THREAD

**Issue by shaardie** [emissions-api/infrastructure#8]
Our current configuration only delivers our API via `HTTP` and not via `HTTPS`. The main reason for that is the missing TLS certificate for our domain `demo.emissions-api.org`.

[Let's Encrypt](https://letsencrypt.org/de/) offers free certificates. Those certificates are only valid for a short period of time, but there are tools which automatically renew those certificates. We should install and configure one of those tools on our machine.

Let's Encrypt offers a list of [different clients](https://letsencrypt.org/docs/client-options/) with [Certbot](https://certbot.eff.org/) being probably the most widely used.

There is the possibility to get a certificate for either `*.emissions-api.org` (via DNS Entries) or `demo.emissions-api.org`, but I tend to the later, since if our machine gets compromised the attacker does not get a wildcard certificate.

Bonus points in this issues can be achieved, if the setup for this is automated with [Ansible](https://www.ansible.com/).

**Comment by tibroc** [comment]
I agree that at this points we should only need certificates for `demo.emissions-api.org`.

**Comment by lkiesow** [comment]
+1 for no wildcards. We will generate certificates automatically anyway …we can just generate more.
