### ISSUE TITLE
OpenSSH Server Configuration

### ISSUE THREAD

**Issue by shaardie** [emissions-api/infrastructure#9]
We currently are using the default OpenSSH Server Configuration from the pre-configured image from netcup.

This is probably not the most secure configuration (e.g. root access via password) and we should replace it with a configuration that fits our needs.

IMHO we can disable password based login completely. Not only for root, but for all user and only allow public key authentication. There are also ssh clients for windows that support ssh keys.

There are maybe also some ciphers we do not want to support. Like old ones ore maybe ECDSA which is disabled by some Linux distributions AFAIK.

And much more...

We should take a deep dive into the documentation and create a configuration that fits our needs.

**Comment by lkiesow** [comment]
Check Mozilla's [SSH configuration and policy scanner](https://github.com/mozilla/ssh_scan)
